# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
<<<<<<< HEAD
since: 2017
=======
since: 2015
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
<<<<<<< HEAD
  Archives: /archives/
  Tags: /tags
  Categories: /categories
#  Search: /search
  About: /about
=======
  # Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  # About: /about
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02

# ===========================================
# Theme Settings
# ===========================================
<<<<<<< HEAD
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  fancybox: true
  search: true
=======
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
color: Default

toc: true

# jQuery fancybox
fancybox: true

pjax: true
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
<<<<<<< HEAD
  email: littledonkeyiphone AT icloud.com
=======
  email: your@email.com
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
<<<<<<< HEAD
  github: https://github.com/liuyou2015
=======
  github: https://github.com/ahonn
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

<<<<<<< HEAD
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

=======
#LiveRe
livere_datauid:
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02

# ===========================================
# Version
# ===========================================
<<<<<<< HEAD
version: 2.6.0
=======
version: 2.9.0
>>>>>>> f897cd88f3de76238b98270a86d50dcdaa906d02
